import '../models/models.dart';

class DummyData {
  static List<Program> get initialPrograms => [
    Program(
      id: 'p1',
      number: 'PRG-101',
      studentName: 'Muhammad Hamdan',
      studentPhoto: 'https://i.pravatar.cc/150?img=11',
      studentClass: 'Senior',
      category: 'Qira\'at (Quran Recitation)',
      item: 'Surah Ar-Rahman Recitation',
      durationMinutes: 12,
      stage: 'Main Stage A',
      status: ProgramStatus.live,
      startTime: '09:00 AM',
      teacher: 'Usthad Ahmed Musliyar',
      remarks: 'Requires 2 condenser microphones',
      priority: 'High',
      colorTag: '#0F766E',
    ),
    Program(
      id: 'p2',
      number: 'PRG-102',
      studentName: 'Abdul Rahman Al-Bashir',
      studentPhoto: 'https://i.pravatar.cc/150?img=12',
      studentClass: 'Super Senior',
      category: 'Na\'at (Mawlid Praise)',
      item: 'Burdah Shareef Recitation',
      durationMinutes: 15,
      stage: 'Main Stage A',
      status: ProgramStatus.pending,
      startTime: '09:15 AM',
      teacher: 'Usthad Shareef Faizy',
      remarks: 'Duff instruments needed',
      priority: 'High',
      colorTag: '#14B8A6',
    ),
    Program(
      id: 'p3',
      number: 'PRG-103',
      studentName: 'Fatima Zohra',
      studentPhoto: 'https://i.pravatar.cc/150?img=5',
      studentClass: 'Junior',
      category: 'Speech (Elocution)',
      item: 'Seerah: Prophet\'s Mercy to Mankind',
      durationMinutes: 10,
      stage: 'Auditorium Stage B',
      status: ProgramStatus.completed,
      startTime: '08:30 AM',
      teacher: 'Usthadh Zainab Beevi',
      remarks: 'Podium presentation',
      priority: 'Normal',
      colorTag: '#D4AF37',
    ),
    Program(
      id: 'p4',
      number: 'PRG-104',
      studentName: 'Zayd Ibn Harith',
      studentPhoto: 'https://i.pravatar.cc/150?img=15',
      studentClass: 'Sub-Junior',
      category: 'Group Song',
      item: 'Milad An-Nabi Arabic Choir',
      durationMinutes: 15,
      stage: 'Main Stage A',
      status: ProgramStatus.pending,
      startTime: '09:35 AM',
      teacher: 'Usthad Bilal Hudawi',
      remarks: 'Group of 8 students',
      priority: 'Normal',
      colorTag: '#10B981',
    ),
    Program(
      id: 'p5',
      number: 'PRG-105',
      studentName: 'Bilal Hassan',
      studentPhoto: 'https://i.pravatar.cc/150?img=33',
      studentClass: 'Senior',
      category: 'Islamic Quiz',
      item: 'Grand Seerah & Fiqh Bowl',
      durationMinutes: 20,
      stage: 'Hall C',
      status: ProgramStatus.pending,
      startTime: '10:00 AM',
      teacher: 'Usthad Usman Saqafi',
      remarks: 'Buzzer system active',
      priority: 'High',
      colorTag: '#3B82F6',
    ),
    Program(
      id: 'p6',
      number: 'PRG-106',
      studentName: 'Umar Farooq',
      studentPhoto: 'https://i.pravatar.cc/150?img=53',
      studentClass: 'Junior',
      category: 'Calligraphy',
      item: 'Live Thuluth Arabic Calligraphy',
      durationMinutes: 30,
      stage: 'Art Gallery Area',
      status: ProgramStatus.completed,
      startTime: '08:00 AM',
      teacher: 'Usthad Khalid Al-Khattat',
      remarks: 'Easel board & inks set up',
      priority: 'Normal',
      colorTag: '#F59E0B',
    ),
    Program(
      id: 'p7',
      number: 'PRG-107',
      studentName: 'Aisha Siddiqua',
      studentPhoto: 'https://i.pravatar.cc/150?img=9',
      studentClass: 'Super Senior',
      category: 'Speech (Elocution)',
      item: 'The Golden Age of Islamic Science',
      durationMinutes: 12,
      stage: 'Auditorium Stage B',
      status: ProgramStatus.pending,
      startTime: '10:25 AM',
      teacher: 'Usthadh Mariyam Saqafiyya',
      remarks: 'Screen display for slides',
      priority: 'Normal',
      colorTag: '#8B5CF6',
    ),
    Program(
      id: 'p8',
      number: 'PRG-108',
      studentName: 'Yusuf Mansoor',
      studentPhoto: 'https://i.pravatar.cc/150?img=60',
      studentClass: 'Sub-Junior',
      category: 'Qira\'at (Quran Recitation)',
      item: 'Surah An-Naba Recitation',
      durationMinutes: 8,
      stage: 'Main Stage A',
      status: ProgramStatus.pending,
      startTime: '10:40 AM',
      teacher: 'Usthad Ahmed Musliyar',
      remarks: 'Microphone height adjustment',
      priority: 'Low',
      colorTag: '#EC4899',
    ),
  ];

  static List<Participant> get initialParticipants => [
    Participant(
      id: 'part-1',
      name: 'Muhammad Hamdan',
      photoUrl: 'https://i.pravatar.cc/150?img=11',
      studentClass: 'Senior',
      category: 'Qira\'at',
      item: 'Surah Ar-Rahman',
      teacher: 'Usthad Ahmed Musliyar',
      madrasaName: 'Al-Azhar Central Madrasa',
      status: 'Live On Stage',
    ),
    Participant(
      id: 'part-2',
      name: 'Abdul Rahman Al-Bashir',
      photoUrl: 'https://i.pravatar.cc/150?img=12',
      studentClass: 'Super Senior',
      category: 'Na\'at',
      item: 'Burdah Shareef',
      teacher: 'Usthad Shareef Faizy',
      madrasaName: 'Sirajul Huda Academy',
      status: 'Up Next',
    ),
    Participant(
      id: 'part-3',
      name: 'Fatima Zohra',
      photoUrl: 'https://i.pravatar.cc/150?img=5',
      studentClass: 'Junior',
      category: 'Speech',
      item: 'Seerah Study',
      teacher: 'Usthadh Zainab Beevi',
      madrasaName: 'Al-Hidayah Islamic Centre',
      status: 'Completed',
    ),
    Participant(
      id: 'part-4',
      name: 'Zayd Ibn Harith',
      photoUrl: 'https://i.pravatar.cc/150?img=15',
      studentClass: 'Sub-Junior',
      category: 'Group Song',
      item: 'Milad Arabic Choir',
      teacher: 'Usthad Bilal Hudawi',
      madrasaName: 'Markazu Saqafati Sunniyya',
      status: 'Scheduled',
    ),
    Participant(
      id: 'part-5',
      name: 'Bilal Hassan',
      photoUrl: 'https://i.pravatar.cc/150?img=33',
      studentClass: 'Senior',
      category: 'Quiz',
      item: 'Seerah Bowl',
      teacher: 'Usthad Usman Saqafi',
      madrasaName: 'Al-Madina Public Campus',
      status: 'Scheduled',
    ),
  ];

  static List<MadrasaModel> get initialMadrasas => [
        MadrasaModel(
          madrasaId: 'reg101@tanzeem',
          madrasaName: 'Al-Azhar Central Madrasa',
          madrasaRegNo: 'REG101',
          address: 'Grand Campus, Calicut',
          coordinatorName: 'Usthad Ahmed',
          coordinatorPhone: '+91 9876543210',
          email: 'ahmed@reg101.tanzeem',
          password: 'usthadahmed@reg101',
          createdAt: '2026-08-01 10:00 AM',
        ),
        MadrasaModel(
          madrasaId: 'reg102@tanzeem',
          madrasaName: 'Sirajul Huda Model Academy',
          madrasaRegNo: 'REG102',
          address: 'Kuttiadi Zone, Kozhikode',
          coordinatorName: 'Usthad Shareef',
          coordinatorPhone: '+91 9876543211',
          email: 'shareef@reg102.tanzeem',
          password: 'usthadshareef@reg102',
          createdAt: '2026-08-01 11:30 AM',
        ),
        MadrasaModel(
          madrasaId: 'reg103@tanzeem',
          madrasaName: 'Al-Hidayah Islamic Complex',
          madrasaRegNo: 'REG103',
          address: 'Malappuram East',
          coordinatorName: 'Usthad Bilal',
          coordinatorPhone: '+91 9876543212',
          email: 'bilal@reg103.tanzeem',
          password: 'usthadbilal@reg103',
          createdAt: '2026-08-01 02:15 PM',
        ),
        MadrasaModel(
          madrasaId: 'reg104@tanzeem',
          madrasaName: 'Markaz Knowledge City Madrasa',
          madrasaRegNo: 'REG104',
          address: 'Kanthapuram Campus',
          coordinatorName: 'Usthad Usman',
          coordinatorPhone: '+91 9876543213',
          email: 'usman@reg104.tanzeem',
          password: 'usthadusman@reg104',
          createdAt: '2026-08-01 04:45 PM',
        ),
      ];

  static List<NotificationItem> get initialNotifications => [
    NotificationItem(
      id: 'n1',
      title: 'Program PRG-101 is Live',
      message: 'Muhammad Hamdan started Qira\'at on Main Stage A.',
      timestamp: '2 mins ago',
      type: 'live',
    ),
    NotificationItem(
      id: 'n2',
      title: 'Schedule Recalculated',
      message: 'Dhuhr Prayer break inserted at 01:00 PM automatically.',
      timestamp: '15 mins ago',
      type: 'update',
    ),
    NotificationItem(
      id: 'n3',
      title: 'New Participant Registered',
      message: 'Abdul Rahman Al-Bashir assigned to Stage A.',
      timestamp: '1 hour ago',
      type: 'participant',
    ),
  ];

  static const List<String> classes = ['Sub-Junior', 'Junior', 'Senior', 'Super Senior'];

  static const List<String> categories = [
    'Qira\'at (Quran Recitation)',
    'Na\'at (Mawlid Praise)',
    'Speech (Elocution)',
    'Group Song',
    'Islamic Quiz',
    'Calligraphy & Arts',
  ];

  static const List<String> stages = [
    'Main Stage A',
    'Auditorium Stage B',
    'Hall C',
    'Art Gallery Area',
  ];
}
